services:
  backend:
    build:
      context: ./
    container_name: request-catcher-backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8086
    ports:
      - "8086:8086"
    volumes:
      - ./app:/app/app
      - ./request_logs.db:/app/request_logs.db
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1

